/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AAtribuicaoComando extends PComando
{
    private PAtrib _atrib_;
    private PListaPontoVirgula _listaPontoVirgula_;

    public AAtribuicaoComando()
    {
        // Constructor
    }

    public AAtribuicaoComando(
        @SuppressWarnings("hiding") PAtrib _atrib_,
        @SuppressWarnings("hiding") PListaPontoVirgula _listaPontoVirgula_)
    {
        // Constructor
        setAtrib(_atrib_);

        setListaPontoVirgula(_listaPontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AAtribuicaoComando(
            cloneNode(this._atrib_),
            cloneNode(this._listaPontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribuicaoComando(this);
    }

    public PAtrib getAtrib()
    {
        return this._atrib_;
    }

    public void setAtrib(PAtrib node)
    {
        if(this._atrib_ != null)
        {
            this._atrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atrib_ = node;
    }

    public PListaPontoVirgula getListaPontoVirgula()
    {
        return this._listaPontoVirgula_;
    }

    public void setListaPontoVirgula(PListaPontoVirgula node)
    {
        if(this._listaPontoVirgula_ != null)
        {
            this._listaPontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaPontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atrib_)
            + toString(this._listaPontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atrib_ == child)
        {
            this._atrib_ = null;
            return;
        }

        if(this._listaPontoVirgula_ == child)
        {
            this._listaPontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atrib_ == oldChild)
        {
            setAtrib((PAtrib) newChild);
            return;
        }

        if(this._listaPontoVirgula_ == oldChild)
        {
            setListaPontoVirgula((PListaPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
