/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AAuxPara extends PAuxPara
{
    private PListaAtrib _listaAtrib_;
    private PListaPontoVirgula _listaPontoVirgula_;

    public AAuxPara()
    {
        // Constructor
    }

    public AAuxPara(
        @SuppressWarnings("hiding") PListaAtrib _listaAtrib_,
        @SuppressWarnings("hiding") PListaPontoVirgula _listaPontoVirgula_)
    {
        // Constructor
        setListaAtrib(_listaAtrib_);

        setListaPontoVirgula(_listaPontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AAuxPara(
            cloneNode(this._listaAtrib_),
            cloneNode(this._listaPontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAuxPara(this);
    }

    public PListaAtrib getListaAtrib()
    {
        return this._listaAtrib_;
    }

    public void setListaAtrib(PListaAtrib node)
    {
        if(this._listaAtrib_ != null)
        {
            this._listaAtrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaAtrib_ = node;
    }

    public PListaPontoVirgula getListaPontoVirgula()
    {
        return this._listaPontoVirgula_;
    }

    public void setListaPontoVirgula(PListaPontoVirgula node)
    {
        if(this._listaPontoVirgula_ != null)
        {
            this._listaPontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaPontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaAtrib_)
            + toString(this._listaPontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaAtrib_ == child)
        {
            this._listaAtrib_ = null;
            return;
        }

        if(this._listaPontoVirgula_ == child)
        {
            this._listaPontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaAtrib_ == oldChild)
        {
            setListaAtrib((PListaAtrib) newChild);
            return;
        }

        if(this._listaPontoVirgula_ == oldChild)
        {
            setListaPontoVirgula((PListaPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
