/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class ABloco extends PBloco
{
    private TInicio _inicio_;
    private PListaDec _listaDec_;
    private PListaComando _listaComando_;
    private TFim _fim_;

    public ABloco()
    {
        // Constructor
    }

    public ABloco(
        @SuppressWarnings("hiding") TInicio _inicio_,
        @SuppressWarnings("hiding") PListaDec _listaDec_,
        @SuppressWarnings("hiding") PListaComando _listaComando_,
        @SuppressWarnings("hiding") TFim _fim_)
    {
        // Constructor
        setInicio(_inicio_);

        setListaDec(_listaDec_);

        setListaComando(_listaComando_);

        setFim(_fim_);

    }

    @Override
    public Object clone()
    {
        return new ABloco(
            cloneNode(this._inicio_),
            cloneNode(this._listaDec_),
            cloneNode(this._listaComando_),
            cloneNode(this._fim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloco(this);
    }

    public TInicio getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(TInicio node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    public PListaDec getListaDec()
    {
        return this._listaDec_;
    }

    public void setListaDec(PListaDec node)
    {
        if(this._listaDec_ != null)
        {
            this._listaDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDec_ = node;
    }

    public PListaComando getListaComando()
    {
        return this._listaComando_;
    }

    public void setListaComando(PListaComando node)
    {
        if(this._listaComando_ != null)
        {
            this._listaComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando_ = node;
    }

    public TFim getFim()
    {
        return this._fim_;
    }

    public void setFim(TFim node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inicio_)
            + toString(this._listaDec_)
            + toString(this._listaComando_)
            + toString(this._fim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        if(this._listaDec_ == child)
        {
            this._listaDec_ = null;
            return;
        }

        if(this._listaComando_ == child)
        {
            this._listaComando_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inicio_ == oldChild)
        {
            setInicio((TInicio) newChild);
            return;
        }

        if(this._listaDec_ == oldChild)
        {
            setListaDec((PListaDec) newChild);
            return;
        }

        if(this._listaComando_ == oldChild)
        {
            setListaComando((PListaComando) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((TFim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
