/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AComSeComando extends PComando
{
    private PComandoSenao _comandoSenao_;

    public AComSeComando()
    {
        // Constructor
    }

    public AComSeComando(
        @SuppressWarnings("hiding") PComandoSenao _comandoSenao_)
    {
        // Constructor
        setComandoSenao(_comandoSenao_);

    }

    @Override
    public Object clone()
    {
        return new AComSeComando(
            cloneNode(this._comandoSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComSeComando(this);
    }

    public PComandoSenao getComandoSenao()
    {
        return this._comandoSenao_;
    }

    public void setComandoSenao(PComandoSenao node)
    {
        if(this._comandoSenao_ != null)
        {
            this._comandoSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoSenao_ == child)
        {
            this._comandoSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoSenao_ == oldChild)
        {
            setComandoSenao((PComandoSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
