/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AComandoParaCada extends PComandoParaCada
{
    private TParacada _paracada_;
    private TAbreparenteses _abreparenteses_;
    private PAuxParaCada _auxParaCada_;
    private TFechaparenteses _fechaparenteses_;
    private PComando _comando_;

    public AComandoParaCada()
    {
        // Constructor
    }

    public AComandoParaCada(
        @SuppressWarnings("hiding") TParacada _paracada_,
        @SuppressWarnings("hiding") TAbreparenteses _abreparenteses_,
        @SuppressWarnings("hiding") PAuxParaCada _auxParaCada_,
        @SuppressWarnings("hiding") TFechaparenteses _fechaparenteses_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setParacada(_paracada_);

        setAbreparenteses(_abreparenteses_);

        setAuxParaCada(_auxParaCada_);

        setFechaparenteses(_fechaparenteses_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AComandoParaCada(
            cloneNode(this._paracada_),
            cloneNode(this._abreparenteses_),
            cloneNode(this._auxParaCada_),
            cloneNode(this._fechaparenteses_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoParaCada(this);
    }

    public TParacada getParacada()
    {
        return this._paracada_;
    }

    public void setParacada(TParacada node)
    {
        if(this._paracada_ != null)
        {
            this._paracada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paracada_ = node;
    }

    public TAbreparenteses getAbreparenteses()
    {
        return this._abreparenteses_;
    }

    public void setAbreparenteses(TAbreparenteses node)
    {
        if(this._abreparenteses_ != null)
        {
            this._abreparenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreparenteses_ = node;
    }

    public PAuxParaCada getAuxParaCada()
    {
        return this._auxParaCada_;
    }

    public void setAuxParaCada(PAuxParaCada node)
    {
        if(this._auxParaCada_ != null)
        {
            this._auxParaCada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._auxParaCada_ = node;
    }

    public TFechaparenteses getFechaparenteses()
    {
        return this._fechaparenteses_;
    }

    public void setFechaparenteses(TFechaparenteses node)
    {
        if(this._fechaparenteses_ != null)
        {
            this._fechaparenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaparenteses_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paracada_)
            + toString(this._abreparenteses_)
            + toString(this._auxParaCada_)
            + toString(this._fechaparenteses_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paracada_ == child)
        {
            this._paracada_ = null;
            return;
        }

        if(this._abreparenteses_ == child)
        {
            this._abreparenteses_ = null;
            return;
        }

        if(this._auxParaCada_ == child)
        {
            this._auxParaCada_ = null;
            return;
        }

        if(this._fechaparenteses_ == child)
        {
            this._fechaparenteses_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paracada_ == oldChild)
        {
            setParacada((TParacada) newChild);
            return;
        }

        if(this._abreparenteses_ == oldChild)
        {
            setAbreparenteses((TAbreparenteses) newChild);
            return;
        }

        if(this._auxParaCada_ == oldChild)
        {
            setAuxParaCada((PAuxParaCada) newChild);
            return;
        }

        if(this._fechaparenteses_ == oldChild)
        {
            setFechaparenteses((TFechaparenteses) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
