/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AComando extends PComando
{
    private PComandoSe _comandoSe_;

    public AComando()
    {
        // Constructor
    }

    public AComando(
        @SuppressWarnings("hiding") PComandoSe _comandoSe_)
    {
        // Constructor
        setComandoSe(_comandoSe_);

    }

    @Override
    public Object clone()
    {
        return new AComando(
            cloneNode(this._comandoSe_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComando(this);
    }

    public PComandoSe getComandoSe()
    {
        return this._comandoSe_;
    }

    public void setComandoSe(PComandoSe node)
    {
        if(this._comandoSe_ != null)
        {
            this._comandoSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSe_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoSe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoSe_ == child)
        {
            this._comandoSe_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoSe_ == oldChild)
        {
            setComandoSe((PComandoSe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
