/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AExpr extends PExpr
{
    private PTipoEsp _tipoEsp_;

    public AExpr()
    {
        // Constructor
    }

    public AExpr(
        @SuppressWarnings("hiding") PTipoEsp _tipoEsp_)
    {
        // Constructor
        setTipoEsp(_tipoEsp_);

    }

    @Override
    public Object clone()
    {
        return new AExpr(
            cloneNode(this._tipoEsp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpr(this);
    }

    public PTipoEsp getTipoEsp()
    {
        return this._tipoEsp_;
    }

    public void setTipoEsp(PTipoEsp node)
    {
        if(this._tipoEsp_ != null)
        {
            this._tipoEsp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoEsp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoEsp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoEsp_ == child)
        {
            this._tipoEsp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoEsp_ == oldChild)
        {
            setTipoEsp((PTipoEsp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
