/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AListaListaComando extends PListaComando
{
    private PListaComando1 _listaComando1_;

    public AListaListaComando()
    {
        // Constructor
    }

    public AListaListaComando(
        @SuppressWarnings("hiding") PListaComando1 _listaComando1_)
    {
        // Constructor
        setListaComando1(_listaComando1_);

    }

    @Override
    public Object clone()
    {
        return new AListaListaComando(
            cloneNode(this._listaComando1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaListaComando(this);
    }

    public PListaComando1 getListaComando1()
    {
        return this._listaComando1_;
    }

    public void setListaComando1(PListaComando1 node)
    {
        if(this._listaComando1_ != null)
        {
            this._listaComando1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaComando1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaComando1_ == child)
        {
            this._listaComando1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaComando1_ == oldChild)
        {
            setListaComando1((PListaComando1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
