/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AListaComListaComando1 extends PListaComando1
{
    private PComando _comando_;
    private PListaComando1 _listaComando1_;

    public AListaComListaComando1()
    {
        // Constructor
    }

    public AListaComListaComando1(
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") PListaComando1 _listaComando1_)
    {
        // Constructor
        setComando(_comando_);

        setListaComando1(_listaComando1_);

    }

    @Override
    public Object clone()
    {
        return new AListaComListaComando1(
            cloneNode(this._comando_),
            cloneNode(this._listaComando1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaComListaComando1(this);
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public PListaComando1 getListaComando1()
    {
        return this._listaComando1_;
    }

    public void setListaComando1(PListaComando1 node)
    {
        if(this._listaComando1_ != null)
        {
            this._listaComando1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comando_)
            + toString(this._listaComando1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._listaComando1_ == child)
        {
            this._listaComando1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._listaComando1_ == oldChild)
        {
            setListaComando1((PListaComando1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
