/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AListaListaDec extends PListaDec
{
    private PListaDec1 _listaDec1_;

    public AListaListaDec()
    {
        // Constructor
    }

    public AListaListaDec(
        @SuppressWarnings("hiding") PListaDec1 _listaDec1_)
    {
        // Constructor
        setListaDec1(_listaDec1_);

    }

    @Override
    public Object clone()
    {
        return new AListaListaDec(
            cloneNode(this._listaDec1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaListaDec(this);
    }

    public PListaDec1 getListaDec1()
    {
        return this._listaDec1_;
    }

    public void setListaDec1(PListaDec1 node)
    {
        if(this._listaDec1_ != null)
        {
            this._listaDec1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDec1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaDec1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaDec1_ == child)
        {
            this._listaDec1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaDec1_ == oldChild)
        {
            setListaDec1((PListaDec1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
