/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AOpBoolOperadores extends POperadores
{
    private PExpr _expr_;
    private POpBool _opBool_;
    private PFator _fator_;

    public AOpBoolOperadores()
    {
        // Constructor
    }

    public AOpBoolOperadores(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") POpBool _opBool_,
        @SuppressWarnings("hiding") PFator _fator_)
    {
        // Constructor
        setExpr(_expr_);

        setOpBool(_opBool_);

        setFator(_fator_);

    }

    @Override
    public Object clone()
    {
        return new AOpBoolOperadores(
            cloneNode(this._expr_),
            cloneNode(this._opBool_),
            cloneNode(this._fator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpBoolOperadores(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public POpBool getOpBool()
    {
        return this._opBool_;
    }

    public void setOpBool(POpBool node)
    {
        if(this._opBool_ != null)
        {
            this._opBool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opBool_ = node;
    }

    public PFator getFator()
    {
        return this._fator_;
    }

    public void setFator(PFator node)
    {
        if(this._fator_ != null)
        {
            this._fator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._opBool_)
            + toString(this._fator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._opBool_ == child)
        {
            this._opBool_ = null;
            return;
        }

        if(this._fator_ == child)
        {
            this._fator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._opBool_ == oldChild)
        {
            setOpBool((POpBool) newChild);
            return;
        }

        if(this._fator_ == oldChild)
        {
            setFator((PFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
