/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AParaComando extends PComando
{
    private PComandoPara _comandoPara_;

    public AParaComando()
    {
        // Constructor
    }

    public AParaComando(
        @SuppressWarnings("hiding") PComandoPara _comandoPara_)
    {
        // Constructor
        setComandoPara(_comandoPara_);

    }

    @Override
    public Object clone()
    {
        return new AParaComando(
            cloneNode(this._comandoPara_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaComando(this);
    }

    public PComandoPara getComandoPara()
    {
        return this._comandoPara_;
    }

    public void setComandoPara(PComandoPara node)
    {
        if(this._comandoPara_ != null)
        {
            this._comandoPara_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoPara_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoPara_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoPara_ == child)
        {
            this._comandoPara_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoPara_ == oldChild)
        {
            setComandoPara((PComandoPara) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
