/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class ATipoEsp extends PTipoEsp
{
    private TInteiroLiteral _inteiroLiteral_;

    public ATipoEsp()
    {
        // Constructor
    }

    public ATipoEsp(
        @SuppressWarnings("hiding") TInteiroLiteral _inteiroLiteral_)
    {
        // Constructor
        setInteiroLiteral(_inteiroLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ATipoEsp(
            cloneNode(this._inteiroLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoEsp(this);
    }

    public TInteiroLiteral getInteiroLiteral()
    {
        return this._inteiroLiteral_;
    }

    public void setInteiroLiteral(TInteiroLiteral node)
    {
        if(this._inteiroLiteral_ != null)
        {
            this._inteiroLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inteiroLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inteiroLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inteiroLiteral_ == child)
        {
            this._inteiroLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inteiroLiteral_ == oldChild)
        {
            setInteiroLiteral((TInteiroLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
