/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AVetorTipo extends PTipo
{
    private TVetor _vetor_;
    private PTipoBase _tipoBase_;

    public AVetorTipo()
    {
        // Constructor
    }

    public AVetorTipo(
        @SuppressWarnings("hiding") TVetor _vetor_,
        @SuppressWarnings("hiding") PTipoBase _tipoBase_)
    {
        // Constructor
        setVetor(_vetor_);

        setTipoBase(_tipoBase_);

    }

    @Override
    public Object clone()
    {
        return new AVetorTipo(
            cloneNode(this._vetor_),
            cloneNode(this._tipoBase_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorTipo(this);
    }

    public TVetor getVetor()
    {
        return this._vetor_;
    }

    public void setVetor(TVetor node)
    {
        if(this._vetor_ != null)
        {
            this._vetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vetor_ = node;
    }

    public PTipoBase getTipoBase()
    {
        return this._tipoBase_;
    }

    public void setTipoBase(PTipoBase node)
    {
        if(this._tipoBase_ != null)
        {
            this._tipoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoBase_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vetor_)
            + toString(this._tipoBase_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vetor_ == child)
        {
            this._vetor_ = null;
            return;
        }

        if(this._tipoBase_ == child)
        {
            this._tipoBase_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vetor_ == oldChild)
        {
            setVetor((TVetor) newChild);
            return;
        }

        if(this._tipoBase_ == oldChild)
        {
            setTipoBase((PTipoBase) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
