/* This file was generated by SableCC (http://www.sablecc.org/). */

package Mangaba.node;

import Mangaba.analysis.*;

@SuppressWarnings("nls")
public final class TNao extends Token
{
    public TNao()
    {
        super.setText("não");
    }

    public TNao(int line, int pos)
    {
        super.setText("não");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNao text.");
    }
}
